# Generated by Django 2.2.5 on 2020-01-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofileinfo',
            name='username_vendor',
        ),
    ]
