# Generated by Django 2.2.5 on 2020-01-31 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_remove_custprofileinfo_username_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='custprofileinfo',
            name='has_ordered_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custprofileinfo',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofileinfo',
            name='order_history',
            field=models.FileField(default=None, upload_to='order_file/'),
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.VendorProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_complete', models.BooleanField(default=False)),
                ('cost', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.CustProfileInfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.SoldItem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.CustProfileInfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.SoldItem')),
            ],
        ),
    ]
