# Generated by Django 2.2.5 on 2020-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200131_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='custprofileinfo',
            name='wallet_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='picture',
            field=models.ImageField(upload_to='item_photo/'),
        ),
    ]
