# Generated by Django 2.2.5 on 2020-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200131_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='picture',
            field=models.ImageField(blank=True, upload_to='item_photo'),
        ),
    ]
