# Generated by Django 2.2.5 on 2020-02-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200201_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.CustProfileInfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.SoldItem')),
            ],
        ),
    ]
