# Generated by Django 2.2.5 on 2020-02-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20200202_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custprofileinfo',
            name='has_ordered_item',
        ),
    ]
